services:
    mongodb:
        image: mongo:latest
        container_name: "mongo-db"
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
volumes:
    mongodb:
    mongodb_config:

